#!/bin/bash

if ! [ -d "$(xcode-select -p)" ]; then
  echo "Installing command line tools. After installation rerun the script again."
  xcode-select --install; exit 0
fi

DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

mkdir -p ~/.ssh
mkdir -p ~/.local/bin
mkdir -p ~/.config

cp "$DIR"/CommitMono/*.otf ~/Library/Fonts/
cp -R "$DIR/zed" "$HOME/.config"

rm ~/.zshrc 2&>/dev/null || true; cp "$DIR/.zshrc" ~/.zshrc
rm ~/.gitconfig 2&>/dev/null || true; cp "$DIR/.gitconfig" ~/.gitconfig
rm ~/.clang-format 2&>/dev/null || true; cp "$DIR/.clang-format" ~/.clang-format
rm ~/.clangd 2&>/dev/null || true; cp "$DIR/.clangd" ~/.clangd

chown -R $(whoami) ~/.ssh/
chmod 700 ~/.ssh
touch ~/.pgpass
chmod 600 ~/.pgpass

git config --global user.name "Sushant Kumar"
git config --global user.email "sushant.mithila@gmail.com"

# load custom env vars from this file like above
if ! [ -f ~/.custom.sh ]; then
  touch ~/.custom.sh
  cat >~/.custom.sh  <<EOL
# === terraform access for aws user: terraform-admin
# export AWS_DEFAULT_REGION="ap-south-1"
# export AWS_ACCESS_KEY_ID="BKIAWW2WGKE44VKNY5E2"
# export AWS_SECRET_ACCESS_KEY="Pv4trKM6N/Uy2lcNn5vCAKA2DgBPEYTIwmF/fMVY"
# === terraform git clone token
# export TF_VAR_github_api_token="github_pat_11BBTADNI0OOYrM8qbrqwz_S9zaH3mWVCdPXG2HBMUC721CGM9"
EOL
fi

if ! [ -f ~/.ssh/config ]; then
  touch ~/.ssh/config
  cat >~/.ssh/config  <<EOL
Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
EOL
fi

osascript -e 'tell application "System Preferences" to quit'
defaults write -g KeyRepeat -int 2 || true
defaults write -g InitialKeyRepeat -int 10 || true
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false || true
defaults delete -g ApplePressAndHoldEnabled || true
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
defaults write com.apple.Terminal ShowLineMarks -int 0
defaults write com.apple.TextEdit RichText -int 0
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticDownload -boolean false
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate ConfigDataInstall -boolean false
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate CriticalUpdateInstall -boolean false
defaults write com.apple.finder "FXPreferredViewStyle" -string "Nlsv" && killall Finder
defaults write com.apple.finder NewWindowTargetPath -string "file://$HOME/Downloads"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.dock show-recents -bool false

# run binary faster: https://nexte.st/docs/installation/macos/#gatekeeper
sudo spctl developer-mode enable-terminal

export PATH="$HOME/.cargo/bin:$HOME/.pyenv/shims:$HOME/.local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:$PATH"

if type brew &>/dev/null; then
  brew upgrade --greedy
else
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

for cask in iterm2 zed@preview firefox@developer-edition alt-tab rectangle; do
  brew install --cask $cask
done
for formula in tree pyenv htop node pkg-config cmake curl wget just cmake protobuf llvm git-lfs awscli ffmpeg; do
  brew install $formula
done
brew services list
brew cleanup --prune=0 -s

git lfs install

for tool in clangd clang-format clang-tidy; do
  if [ -f /opt/homebrew/opt/llvm/bin/$tool ]; then
    rm ~/.local/bin/$tool 2&>/dev/null || true
    ln -sfF /opt/homebrew/opt/llvm/bin/$tool ~/.local/bin/$tool
  fi
done

VER="$(pyenv latest -k 3)"
env PYTHON_CONFIGURE_OPTS="--enable-shared --enable-optimizations --with-lto" \
    PYTHON_CFLAGS='-march=native -mtune=native' \
    pyenv install $VER -vv
pyenv global $VER
pip install --upgrade pip

if type npm &>/dev/null; then
  npm update -g
fi

if ! type rustup &>/dev/null; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi
rustup toolchain install stable
rustup toolchain install nightly
rustup update
for bin in cargo-update cargo-edit; do
  cargo install $bin
done
cd "$DIR/git-prompt" && cargo install --path .

cd ~ && rm -rf .zcompcache .zcompdump*
echo === Done! Restart your machine ===.
