#!/bin/bash

if ! [ -d "$(xcode-select -p)" ]; then
    echo "Installing command line tools. After installation rerun the script again."
    xcode-select --install; exit 0
fi

DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

mkdir -p ~/.ssh ~/.local/bin ~/.config ~/.config/ghostty ~/.cargo
cp -R "$DIR/zed" "$HOME/.config"
for file in .zshrc .gitconfig .clang-format .clangd .vimrc .tmux.conf .config/ghostty/config .cargo/config.toml; do
    cp -f "$DIR/$file" ~/$file
done
git config --global user.name "Sushant Kumar"
git config --global user.email "sushant.mithila@gmail.com"

[ -f ~/.custom.sh ] || cat >~/.custom.sh <<'EOL'
# export AWS_DEFAULT_REGION="ap-south-1"
# export AWS_ACCESS_KEY_ID="------" # terraform access for aws user: terraform-admin
# export AWS_SECRET_ACCESS_KEY="------"
# export TF_VAR_github_api_token="------" # terraform git clone token
EOL

[ -f ~/.ssh/config ] || cat >~/.ssh/config <<'EOL'
Host *
  SetEnv TERM=xterm-256color

Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
EOL

chown -R "$(whoami)" ~/.ssh/ && chmod 700 ~/.ssh
touch ~/.pgpass && chmod 600 ~/.pgpass

osascript -e 'tell application "System Preferences" to quit'
defaults write -g KeyRepeat -int 2
defaults write -g InitialKeyRepeat -int 10
defaults delete -g ApplePressAndHoldEnabled
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
defaults write com.apple.Terminal ShowLineMarks -int 0
defaults write com.apple.TextEdit RichText -int 0
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticDownload -bool false
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate ConfigDataInstall -bool false
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate CriticalUpdateInstall -bool false
defaults write com.apple.finder "FXPreferredViewStyle" -string "Nlsv" && killall Finder
defaults write com.apple.finder NewWindowTargetPath -string "file://$HOME/Downloads"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.dock show-recents -bool false

sudo spctl developer-mode enable-terminal # run binary faster: https://nexte.st/docs/installation/macos/#gatekeeper

export PATH="$HOME/.cargo/bin:$HOME/.pyenv/shims:$HOME/.local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:$PATH"

if type brew &>/dev/null; then
    brew upgrade --greedy
else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
for cask in zed@preview firefox@developer-edition alt-tab rectangle; do
    brew install --cask $cask
done
for formula in tree pyenv htop pkg-config cmake curl wget just cmake protobuf llvm git-lfs tmux \
               awscli ffmpeg font-commit-mono ghostty@tip uv oven-sh/bun/bun; do
    brew install $formula
done
brew cleanup --prune=0 -s

git lfs install

for tool in clangd clang-format clang-tidy; do
    if [ -f /opt/homebrew/opt/llvm/bin/$tool ]; then
        rm ~/.local/bin/$tool 2&>/dev/null || true
        ln -sfF /opt/homebrew/opt/llvm/bin/$tool ~/.local/bin/$tool
    fi
done

VER="$(pyenv latest -k 3)"
PYTHON_CONFIGURE_OPTS="--enable-shared --enable-optimizations --with-lto" PYTHON_CFLAGS='-march=native -mtune=native' pyenv install "$VER" -vv
pyenv global "$VER"
pip install --upgrade pip

if ! type rustup &>/dev/null; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi
rustup update
rustup toolchain install stable nightly
cargo install cargo-update cargo-edit

cd ~ && rm -rf .zcompcache .zcompdump*
echo "=== Done! Restart your machine ==="
